### ISSUE TITLE
Erroneous Theta CFA generation 

### ISSUE THREAD

**Issue by as3810t** [ftsrg/gazer#42]
For input _verif/memory/globals2.c_ (the relevant excerpt):

```
int a = __VERIFIER_nondet_int();
__VERIFIER_assume(a < INT_MAX - 1);
```

the generated CFA is the following (the relevant excerpt):
```
loc2 -> loc8 {
        assume (main_tmp bvslt 32'b01111111111111111111111111111110)
        main_Memory_0_mem := [<bv[64]>default <- 8'd0]
        havoc main_tmp
}
```

The command used to invoke _gazer-theta_: `tools/gazer-theta/gazer-theta --domain EXPL --refinement NWT_IT_WP --maxenum 10 -no-inline-globals test/theta/verif/memory/globals2.c --trace`

As it can be seen, the in the CFA the order of `__VERIFIER_assume` and `__VERIFIER_nondet_int` is swapped, which alters the meaning of the source.

**Comment by as3810t** [comment]
@sallaigy I think I stumbled upon an extremely dangerous bug in the theta backend. I think you should take a look.

**Comment by radl97** [comment]
```
    loc2 -> loc8 {
        assume (not (2147483646 <= main_tmp))
        havoc main_tmp
    }
```

Same with a (minimally modified) master tree

**Comment by radl97** [comment]
Before generating CFA: (with metadata and debug lines removed)

```
define dso_local i32 @main() {
bb:
  call void @gazer.function.entry()
  %tmp = call i32 @__VERIFIER_nondet_int()
  call void @llvm.dbg.value(metadata i32 %tmp)
  %tmp1 = icmp slt i32 %tmp, 2147483646
  call void @verifier.assume(i1 %tmp1)
  %tmp2 = icmp eq i32 %tmp, 0
  %tmp3 = add nsw i32 %tmp, 2
  %storemerge = select i1 %tmp2, i32 1, i32 %tmp3
  %tmp4 = icmp sgt i32 %tmp, %storemerge
  br i1 %tmp4, label %error, label %bb5

bb5:                                              ; preds = %bb
  call void @gazer.function.return_value.i32(i32 0)
  ret i32 0

error:                                            ; preds = %bb
  %error_phi = phi i16 [ 2, %bb ]
  call void @gazer.error_code(i16 %error_phi)
  unreachable
}
```

I think only MemoryModelWrapper and ModuleToAutomataPass remains. So BlocksToCfa should be the problem.

**Comment by radl97** [comment]
With `elim-vars=off`:

```
    loc2 -> loc8 {
        assume main_tmp1
        havoc main_tmp
        main_tmp1 := (not (2147483646 <= main_tmp))
    }
```

Which does not contain the error.

So the problem is related to `bool BlocksToCfa::tryToEliminate`.

**Comment by radl97** [comment]
@sallaigy Can you take a look?

**Comment by radl97** [comment]
This function is suspicious:

https://github.com/ftsrg/gazer/blob/master/src/LLVM/Automaton/ExtensionPoints.cpp#L195

So the pending assigns and the guard is allocated to a new transition. But the guard is "executed" before the assigns... Logically it contradicts.
(The suspicion comes from the __verifier_assume special handling of the function uses this code.)

I will test my theory (and if I'm right, I'll explain more thoroughly :D )

**Comment by radl97** [comment]
@as3810t can you test if this patch fixes the error?

```diff
diff --git a/src/LLVM/Automaton/ExtensionPoints.cpp b/src/LLVM/Automaton/ExtensionPoints.cpp
index f005758..262bdf0 100644
--- a/src/LLVM/Automaton/ExtensionPoints.cpp
+++ b/src/LLVM/Automaton/ExtensionPoints.cpp
@@ -203,7 +203,8 @@ void BlocksToCfa::ExtensionPointImpl::splitCurrentTransition(const ExprPtr& guar
 {
     Location* aux = mGenInfo.Automaton->createLocation();
 
-    mGenInfo.Automaton->createAssignTransition(*mEntry, aux, guard, mAssigns);
+    mGenInfo.Automaton->createAssignTransition(*mEntry, aux, ExprBuilder(guard->getContext()).True(), mAssigns);
+    mGenInfo.Automaton->createAssignTransition(*mEntry, aux, guard, {});
     mAssigns.clear();
 
     *mEntry = aux;
```

**Comment by radl97** [comment]
Don't forget to merge to bitvectors too :) @as3810t
