### ISSUE TITLE
Download fixed Theta binary instead of clone and build

### ISSUE THREAD

**Issue by hajduakos** [ftsrg/gazer#9]
Since Theta is now versioned and binary releases are published, we can just `wget` the (jar and so) binary files instead of cloning and building Theta. This applies both to Travis CI and the Docker image. Besides shorter build time, this would also have the advantage that from now, Gazer would use a fixed version of Theta, avoiding breaking Gazer if there is a breaking change in the current master status of Theta. What do you think @sallaigy? This should be an easy fix, I can do it, but first I'd like your opinion.

**Comment by sallaigy** [comment]
I like this idea and I see two main ways to do it:

1. We could either document which exact Theta version we support and include that one in the Dockerfile and the CI config.
2. Alternatively, we can try add a step into the CMake build script which downloads and extracts Theta automatically in configure time.

The first one is straightforward, the second one involves some black magic but could ease the building process of `gazer-theta`. Not sure it is worth it though, so I would prefer the first solution. What do you think?

**Comment by hajduakos** [comment]
I would also go for the first solution, at least initially as it is very easy. I will work on it.

**Comment by hajduakos** [comment]
Created a separate branch to try it, already works on Travis, also reduces build time from 8 to 5 minutes
